server {
  listen 443 ssl;
  ssl_certificate      /etc/ssl/certs/acme-ai-consulting.crt;
  ssl_certificate_key  /etc/ssl/private/acme-ai-consulting.key;

  server_name acme-ai-consulting.dev www.acme-ai-consulting.dev;

  if ($http_x_forwarded_proto = 'http') {
    set $force_https 1;
  }

  if ($force_https = 1) {
    rewrite ^ https://$host$request_uri? permanent;
  }

  location / {
    proxy_pass http://127.0.0.1:4100;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
